name: Rastreador de Preços

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

jobs:
  executar:

    runs-on: ubuntu-latest

    env:
      EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
      SENHA_EMAIL: ${{ secrets.SENHA_EMAIL }}
      EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}

    steps:

      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar bibliotecas
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Executar script
        run: python main.py